from pathlib import Path

# Path
ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
DEFAULT_MARGIN = 15
MINIMUM_WIDTH = 500

# Style
PRIMARY_COLOR = '#1e81b0'
SEC_COLOR = '#16658a'
TH_COLOR = '#115270'
